### ISSUE TITLE
[Feature] Allow use of PATs for authenticated requests OR use raw.githubusercontent.com

### ISSUE THREAD

**Issue by l-zeuch** [jo3-l/yagfuncdata#1]
### Description

I was trying to implement some form of automation for
l-zeuch/yagpdb.vim and ran into the following error:

```
fetching base context functions: fetching common/templates/context.go
from GitHub: GET
https://api.github.com/repos/botlabs-gg/yagpdb/contents/common/templates/context.go?ref=master:
403 API rate limit exceeded for [IP redacted]. (But here's the good
news: Authenticated requests get a higher rate limit. Check out the
documentation for more details.) [rate reset in 25m57s] 
```

It'd be great if we could provide either a flag or an environment
variable to pass along a GitHub PAT, so that we can avoid this error.

Arguably this is more or less user error, as this program is not
intended to be ran multiple times in quick succession, however exactly
for such development moments it'd be great to have such an option.

For reference, the library you're using to interact with GitHub has
support for this, prominently placed in the README:
https://github.com/google/go-github#authentication

Do note that I'm willing to implement this with an appropriate patch,
however it is kind of rude to just do it and not ask first.

----

Alternatively I think it is sufficient to just use
`raw.githubusercontent.com` instead of `api.github.com` — this is
generally the way install scripts and similar are also shared, if hosted
on GitHub, as that does not require authentication nor is it rate
limited as much as the API.

**Comment by jo3-l** [comment]
PR welcome, thanks.
